"""API routes. Paths are accepted with or without a trailing slash so the React
client and curl behave the same way."""
from django.urls import re_path

from .views import (
    auth,
    bankrec,
    borrowers,
    charges,
    currencies,
    funding,
    groups,
    journals,
    ledger,
    loans,
    org,
    periods,
    products,
    provisions,
    reports,
    savings,
    tills,
)

urlpatterns = [
    # ---- auth and users
    re_path(r"^auth/login/?$", auth.login),
    re_path(r"^auth/login/verify/?$", auth.login_verify),
    re_path(r"^auth/mfa/setup/?$", auth.mfa_setup),
    re_path(r"^auth/mfa/enable/?$", auth.mfa_enable),
    re_path(r"^auth/mfa/disable/?$", auth.mfa_disable),
    re_path(r"^auth/refresh/?$", auth.refresh),
    re_path(r"^auth/logout/?$", auth.logout),
    re_path(r"^auth/sign-out-everywhere/?$", auth.sign_out_everywhere),
    re_path(r"^auth/me/?$", auth.me),
    re_path(r"^auth/change-password/?$", auth.change_password),
    re_path(r"^users/rights/?$", auth.rights),
    re_path(r"^users/?$", auth.users),
    re_path(r"^users/(?P<user_id>\d+)/?$", auth.user_detail),

    # ---- organisation
    re_path(r"^branches/?$", org.branches),
    re_path(r"^branches/(?P<branch_id>\d+)/?$", org.branch_detail),
    re_path(r"^settings/?$", org.settings_view),
    re_path(r"^holidays/?$", org.holidays),
    re_path(r"^holidays/(?P<holiday_id>\d+)/?$", org.holiday_detail),
    re_path(r"^search/?$", org.search),
    re_path(r"^nav-summary/?$", org.nav_summary),

    # ---- borrowers
    re_path(r"^borrowers/?$", borrowers.borrowers),
    re_path(r"^borrowers/(?P<borrower_id>\d+)/?$", borrowers.borrower_detail),
    re_path(r"^borrowers/(?P<borrower_id>\d+)/loans/?$", borrowers.borrower_loans),
    re_path(r"^borrowers/(?P<borrower_id>\d+)/guarantors/?$", borrowers.add_guarantor),
    re_path(r"^borrowers/(?P<borrower_id>\d+)/guarantors/(?P<guarantor_id>\d+)/?$",
            borrowers.remove_guarantor),
    re_path(r"^borrowers/(?P<borrower_id>\d+)/bureau/?$", borrowers.bureau),
    re_path(r"^bureau/status/?$", borrowers.bureau_status),
    re_path(r"^borrowers/(?P<borrower_id>\d+)/documents/?$", borrowers.documents),
    re_path(r"^borrowers/(?P<borrower_id>\d+)/documents/(?P<document_id>\d+)/download/?$",
            borrowers.download_document),
    re_path(r"^borrowers/(?P<borrower_id>\d+)/documents/(?P<document_id>\d+)/?$",
            borrowers.delete_document),

    # ---- products and the charges catalogue
    re_path(r"^products/?$", products.products),
    re_path(r"^products/(?P<product_id>\d+)/?$", products.product_detail),
    re_path(r"^products/(?P<product_id>\d+)/charges/?$", charges.product_charges),
    re_path(r"^charges/?$", charges.charges),
    re_path(r"^charges/(?P<charge_id>\d+)/?$", charges.charge_detail),

    # ---- joint-liability groups
    re_path(r"^groups/?$", groups.groups),
    re_path(r"^groups/performance/?$", groups.performance),
    re_path(r"^groups/(?P<group_id>\d+)/?$", groups.group_detail),
    re_path(r"^groups/(?P<group_id>\d+)/standing/?$", groups.standing),
    re_path(r"^groups/(?P<group_id>\d+)/loans/?$", groups.group_loans),
    re_path(r"^groups/(?P<group_id>\d+)/members/?$", groups.add_member),
    re_path(r"^groups/(?P<group_id>\d+)/members/(?P<member_id>\d+)/?$", groups.member_detail),

    # ---- savings
    re_path(r"^savings/products/?$", savings.products),
    re_path(r"^savings/products/(?P<product_id>\d+)/?$", savings.product_detail),
    re_path(r"^savings/portfolio/?$", savings.portfolio),
    re_path(r"^savings/run-interest/?$", savings.run_interest),
    re_path(r"^savings/accounts/?$", savings.accounts),
    re_path(r"^savings/accounts/(?P<account_id>\d+)/?$", savings.account_detail),
    re_path(r"^savings/accounts/(?P<account_id>\d+)/deposit/?$", savings.deposit),
    re_path(r"^savings/accounts/(?P<account_id>\d+)/withdraw/?$", savings.withdraw),
    re_path(r"^savings/accounts/(?P<account_id>\d+)/close/?$", savings.close),
    re_path(r"^savings/accounts/(?P<account_id>\d+)/statement/?$", savings.statement),
    re_path(r"^savings/accounts/(?P<account_id>\d+)/transactions/(?P<txn_id>\d+)/reverse/?$",
            savings.reverse),

    # ---- loans (quote must come before the numeric id routes)
    re_path(r"^loans/quote/?$", loans.quote),
    re_path(r"^loans/?$", loans.loans),
    re_path(r"^loans/(?P<loan_id>\d+)/?$", loans.loan_detail),
    re_path(r"^loans/(?P<loan_id>\d+)/statement/?$", loans.statement),
    re_path(r"^loans/(?P<loan_id>\d+)/approve/?$", loans.approve),
    re_path(r"^loans/(?P<loan_id>\d+)/reject/?$", loans.reject),
    re_path(r"^loans/(?P<loan_id>\d+)/disburse/?$", loans.disburse),
    re_path(r"^loans/(?P<loan_id>\d+)/repayments/?$", loans.repayments),
    re_path(r"^loans/(?P<loan_id>\d+)/transactions/(?P<txn_id>\d+)/reverse/?$", loans.reverse),
    re_path(r"^loans/(?P<loan_id>\d+)/waive-penalties/?$", loans.waive_penalties),
    re_path(r"^loans/(?P<loan_id>\d+)/write-off/?$", loans.write_off),
    re_path(r"^loans/(?P<loan_id>\d+)/reschedule/?$", loans.reschedule),
    re_path(r"^loans/(?P<loan_id>\d+)/accrue-penalties/?$", loans.accrue_one),
    re_path(r"^loans/(?P<loan_id>\d+)/settlement-quote/?$", loans.settlement_quote),
    re_path(r"^loans/(?P<loan_id>\d+)/settle/?$", loans.settle),
    re_path(r"^loans/(?P<loan_id>\d+)/notes/?$", loans.notes),
    re_path(r"^loans/(?P<loan_id>\d+)/notes/(?P<note_id>\d+)/?$", loans.note_detail),
    re_path(r"^loans/(?P<loan_id>\d+)/recovery/?$", loans.recovery),
    re_path(r"^loans/(?P<loan_id>\d+)/top-up-quote/?$", loans.top_up_quote),
    re_path(r"^loans/(?P<loan_id>\d+)/top-up/?$", loans.top_up),
    re_path(r"^loans/(?P<loan_id>\d+)/charges/?$", loans.raise_charge),
    re_path(r"^loans/(?P<loan_id>\d+)/agreement/?$", loans.agreement),
    re_path(r"^loans/(?P<loan_id>\d+)/guarantors/?$", loans.guarantors),
    re_path(r"^loans/(?P<loan_id>\d+)/collateral/?$", loans.collateral),
    re_path(r"^loans/(?P<loan_id>\d+)/collateral/(?P<collateral_id>\d+)/?$",
            loans.collateral_detail),

    # ---- currencies and the revaluation of foreign-currency loans
    re_path(r"^currencies/?$", currencies.currencies),
    re_path(r"^currencies/rates/?$", currencies.rates),
    re_path(r"^currencies/rates/(?P<rate_id>\d+)/?$", currencies.rate_detail),
    re_path(r"^currencies/revaluations/preview/?$", currencies.revaluation_preview),
    re_path(r"^currencies/revaluations/?$", currencies.revaluations),

    # ---- provisioning (the literal paths must precede the numeric id route)
    re_path(r"^provisions/preview/?$", provisions.preview),
    re_path(r"^provisions/run/?$", provisions.run),
    re_path(r"^provisions/?$", provisions.provisions),
    re_path(r"^provisions/(?P<run_id>\d+)/reverse/?$", provisions.reverse),
    re_path(r"^provisions/(?P<run_id>\d+)/?$", provisions.provision_detail),

    # ---- funding and capital (the literal paths must precede the numeric id routes)
    re_path(r"^funding/summary/?$", funding.summary),
    re_path(r"^funding/accrue-interest/?$", funding.accrue),
    re_path(r"^funding/capital/?$", funding.capital),
    re_path(r"^funding/capital/(?P<txn_id>\d+)/reverse/?$", funding.reverse_capital),
    re_path(r"^funding/facilities/?$", funding.facilities),
    re_path(r"^funding/facilities/(?P<facility_id>\d+)/drawdown/?$", funding.drawdown),
    re_path(r"^funding/facilities/(?P<facility_id>\d+)/repay/?$", funding.repay),
    re_path(r"^funding/facilities/(?P<facility_id>\d+)/interest/?$", funding.pay_interest),
    re_path(r"^funding/facilities/(?P<facility_id>\d+)/fee/?$", funding.charge_fee),
    re_path(r"^funding/facilities/(?P<facility_id>\d+)/close/?$", funding.close),
    re_path(r"^funding/facilities/(?P<facility_id>\d+)/transactions/(?P<txn_id>\d+)/reverse/?$",
            funding.reverse_movement),
    re_path(r"^funding/facilities/(?P<facility_id>\d+)/?$", funding.facility_detail),

    # ---- accounting periods (the literal path must precede the year-month route)
    re_path(r"^periods/status/?$", periods.status),
    re_path(r"^periods/?$", periods.register),
    re_path(r"^periods/(?P<year>\d{4})-(?P<month>\d{1,2})/preflight/?$", periods.preflight),
    re_path(r"^periods/(?P<year>\d{4})-(?P<month>\d{1,2})/close/?$", periods.close),
    re_path(r"^periods/(?P<year>\d{4})-(?P<month>\d{1,2})/reopen/?$", periods.reopen),
    re_path(r"^periods/(?P<year>\d{4})-(?P<month>\d{1,2})/?$", periods.period_detail),

    # ---- general ledger
    re_path(r"^ledger/accounts/?$", ledger.accounts),
    re_path(r"^ledger/accounts/(?P<account_id>\d+)/?$", ledger.account_detail),
    re_path(r"^ledger/journal/?$", ledger.journal),
    re_path(r"^ledger/trial-balance/?$", ledger.trial_balance),
    re_path(r"^ledger/balance-sheet/?$", ledger.balance_sheet),
    re_path(r"^ledger/reconciliation/?$", ledger.reconciliation),
    re_path(r"^ledger/income-statement/?$", ledger.income_statement),
    re_path(r"^ledger/rebuild/?$", ledger.rebuild),
    re_path(r"^ledger/accrue-interest/?$", ledger.accrue_interest),

    # ---- bank and mobile-money reconciliation (line routes before the numeric id ones)
    re_path(r"^bank-statements/lines/(?P<line_id>\d+)/candidates/?$", bankrec.line_candidates),
    re_path(r"^bank-statements/lines/(?P<line_id>\d+)/match/?$", bankrec.line_match),
    re_path(r"^bank-statements/lines/(?P<line_id>\d+)/unmatch/?$", bankrec.line_unmatch),
    re_path(r"^bank-statements/lines/(?P<line_id>\d+)/ignore/?$", bankrec.line_ignore),
    re_path(r"^bank-statements/lines/(?P<line_id>\d+)/journal/?$", bankrec.line_journal),
    re_path(r"^bank-statements/?$", bankrec.statements),
    re_path(r"^bank-statements/(?P<statement_id>\d+)/auto-match/?$", bankrec.auto_match),
    re_path(r"^bank-statements/(?P<statement_id>\d+)/outstanding/?$", bankrec.outstanding),
    re_path(r"^bank-statements/(?P<statement_id>\d+)/?$", bankrec.statement_detail),

    # ---- manual journals: expenses, other income, assets, opening balances
    re_path(r"^journals/?$", journals.journals),
    re_path(r"^journals/(?P<journal_id>\d+)/post/?$", journals.post_journal),
    re_path(r"^journals/(?P<journal_id>\d+)/reject/?$", journals.reject_journal),
    re_path(r"^journals/(?P<journal_id>\d+)/reverse/?$", journals.reverse_journal),
    re_path(r"^journals/(?P<journal_id>\d+)/?$", journals.journal_detail),

    # ---- reports
    re_path(r"^reports/dashboard/?$", reports.dashboard),
    re_path(r"^reports/par/?$", reports.par),
    re_path(r"^reports/arrears-ageing/?$", reports.arrears_ageing),
    re_path(r"^reports/collections-due/?$", reports.collections_due),
    re_path(r"^reports/loan-book/?$", reports.loan_book),
    re_path(r"^reports/transactions/?$", reports.transactions),
    re_path(r"^reports/run-penalties/?$", reports.run_penalties),
    re_path(r"^reports/audit/?$", reports.audit_log),
    re_path(r"^reports/ecl/?$", reports.ecl),
    re_path(r"^reports/officer-performance/?$", reports.officer_performance),
    re_path(r"^reports/product-performance/?$", reports.product_performance),
    re_path(r"^reports/branch-performance/?$", reports.branch_performance),
    re_path(r"^reports/payroll/?$", reports.payroll),
    re_path(r"^reports/employers/?$", reports.employers),
    re_path(r"^reports/spreadsheets/(?P<kind>[a-z-]+)/?$", reports.spreadsheet),
    re_path(r"^reports/workbook/?$", reports.workbook),

    # ---- teller tills (the literal path must precede the numeric id routes)
    re_path(r"^tills/current/?$", tills.current),
    re_path(r"^tills/?$", tills.tills),
    re_path(r"^tills/(?P<till_id>\d+)/count/?$", tills.count),
    re_path(r"^tills/(?P<till_id>\d+)/verify/?$", tills.verify),
    re_path(r"^tills/(?P<till_id>\d+)/?$", tills.till_detail),

    # ---- messaging and batch posting
    re_path(r"^notifications/?$", reports.notifications),
    re_path(r"^notifications/generate/?$", reports.generate_notifications),
    re_path(r"^notifications/send/?$", reports.send_notifications),
    re_path(r"^notifications/mark-sent/?$", reports.mark_notifications_sent),
    re_path(r"^notifications/cancel/?$", reports.cancel_notifications),
    re_path(r"^notifications/gateway/?$", reports.message_gateway),
    re_path(r"^imports/repayments/?$", reports.bulk_repayments),
    re_path(r"^imports/loan-book/?$", reports.loan_book_import),
]
