# Generated by Django 6.1.1 on 2026-09-23 09:42

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('national_id', models.CharField(max_length=40, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('employer', models.CharField(blank=True, max_length=120, null=True)),
                ('employee_no', models.CharField(blank=True, max_length=40, null=True)),
                ('job_title', models.CharField(blank=True, max_length=80, null=True)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('payday', models.IntegerField(default=25, help_text='Day of the month the salary is paid', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('kyc_verified', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'borrowers',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('interest_rate_pct', models.DecimalField(decimal_places=3, help_text='Monthly rate, reducing balance', max_digits=6)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('min_term_months', models.IntegerField()),
                ('max_term_months', models.IntegerField()),
                ('admin_fee_pct', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Deducted upfront', max_digits=6)),
                ('insurance_fee_pct', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Credit life, upfront', max_digits=6)),
                ('penalty_rate_pct_per_day', models.DecimalField(decimal_places=3, default=Decimal('0.5'), max_digits=6)),
                ('grace_days', models.IntegerField(default=3)),
                ('max_instalment_to_salary_pct', models.DecimalField(decimal_places=2, default=Decimal('40'), max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'loan_products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('prefix', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sequences',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('loan_officer', 'Loan officer'), ('teller', 'Teller'), ('viewer', 'Viewer')], default='loan_officer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('entity', models.CharField(max_length=40)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('national_id', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=30)),
                ('relationship_to_borrower', models.CharField(blank=True, max_length=60, null=True)),
                ('employer', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='core.borrower')),
            ],
            options={
                'db_table': 'guarantors',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate_pct', models.DecimalField(decimal_places=3, help_text='Monthly, snapshot from the product', max_digits=6)),
                ('term_months', models.IntegerField()),
                ('purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('instalment_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_interest', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('closed', 'Closed'), ('written_off', 'Written off')], db_index=True, default='pending', max_length=20)),
                ('application_date', models.DateField(default=datetime.date.today)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('first_instalment_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('principal_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('interest_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('penalties_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.borrower')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_loans', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.loanproduct')),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('disbursement', 'Disbursement'), ('repayment', 'Repayment'), ('penalty', 'Penalty'), ('fee', 'Fee'), ('waiver', 'Waiver'), ('write_off', 'Write-off'), ('reversal', 'Reversal')], max_length=20)),
                ('txn_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('principal_component', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('interest_component', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('penalty_component', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('salary_deduction', 'Salary deduction')], max_length=20, null=True)),
                ('reference', models.CharField(blank=True, max_length=80, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('reversed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.loan')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postings', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='core.transaction')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Instalment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('due_date', models.DateField(db_index=True)),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('penalty_due', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('penalty_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('last_penalty_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalments', to='core.loan')),
            ],
            options={
                'db_table': 'instalments',
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('loan', 'number'), name='uq_instalment_loan_number')],
            },
        ),
    ]
