# Generated by Django 6.1.1 on 2026-09-23 10:46

import core.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'branches',
                'db_table': 'branches',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Loan Management System', max_length=160)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('ecl_stage1_pct', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6)),
                ('ecl_stage2_pct', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=6)),
                ('ecl_stage3_pct', models.DecimalField(decimal_places=2, default=Decimal('60'), max_digits=6)),
                ('ecl_stage2_days', models.IntegerField(default=30)),
                ('ecl_stage3_days', models.IntegerField(default=90)),
                ('reminder_days_before', models.IntegerField(default=3)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'organisation_settings',
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='rate_method',
            field=models.CharField(choices=[('reducing', 'Reducing balance'), ('flat', 'Flat rate')], default='reducing', help_text='Snapshot from the product at application', max_length=10),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='rate_method',
            field=models.CharField(choices=[('reducing', 'Reducing balance'), ('flat', 'Flat rate')], default='reducing', help_text='Reducing balance charges interest on the outstanding balance; flat rate charges it on the original principal', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate_pct',
            field=models.DecimalField(decimal_places=3, help_text='Monthly rate', max_digits=6),
        ),
        migrations.CreateModel(
            name='BorrowerDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('id', 'Identity document'), ('payslip', 'Payslip'), ('contract', 'Employment contract'), ('bank_statement', 'Bank statement'), ('agreement', 'Signed loan agreement'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to=core.models.document_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size_bytes', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.borrower')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'borrower_documents',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='borrower',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowers', to='core.branch'),
        ),
        migrations.AddField(
            model_name='loan',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='core.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='core.branch'),
        ),
        migrations.CreateModel(
            name='LoanNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('next_action_date', models.DateField(blank=True, db_index=True, null=True)),
                ('promised_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('promised_date', models.DateField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_notes', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.loan')),
            ],
            options={
                'db_table': 'loan_notes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reminder', 'Instalment reminder'), ('arrears', 'Arrears notice'), ('receipt', 'Repayment receipt'), ('welcome', 'Disbursement confirmation')], max_length=20)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='sms', max_length=10)),
                ('to_address', models.CharField(max_length=160)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=12)),
                ('scheduled_for', models.DateField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.borrower')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.loan')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-id'],
            },
        ),
    ]
