# Generated by Django 6.1.1 on 2026-09-23 11:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_branch_organisationsetting_loan_rate_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ledger_accounts',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='credit_grade',
            field=models.CharField(blank=True, choices=[('A', 'A - very strong'), ('B', 'B - strong'), ('C', 'C - acceptable'), ('D', 'D - marginal'), ('E', 'E - weak')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='credit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='score_detail',
            field=models.TextField(blank=True, help_text='JSON breakdown of how the score was reached', null=True),
        ),
        migrations.AddField(
            model_name='organisationsetting',
            name='min_credit_score',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='organisationsetting',
            name='officer_approval_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(choices=[('disbursement', 'Disbursement'), ('repayment', 'Repayment'), ('penalty', 'Penalty'), ('fee', 'Fee'), ('waiver', 'Waiver'), ('write_off', 'Write-off'), ('recovery', 'Recovery after write-off'), ('reversal', 'Reversal')], max_length=20),
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vehicle', 'Vehicle'), ('property', 'Property'), ('equipment', 'Equipment'), ('livestock', 'Livestock'), ('cash_deposit', 'Cash deposit'), ('guarantee', 'Third-party guarantee'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, help_text='Registration number, title deed, serial number', max_length=80, null=True)),
                ('status', models.CharField(choices=[('pledged', 'Pledged'), ('released', 'Released'), ('realised', 'Realised')], default='pledged', max_length=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collateral', to='core.loan')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collateral_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'collateral',
                'db_table': 'collateral',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('entry_date', models.DateField(db_index=True)),
                ('narration', models.TextField()),
                ('source', models.CharField(help_text='The transaction type that raised it', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.branch')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.loan')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='core.transaction')),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'db_table': 'journal_entries',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.journalentry')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='core.ledgeraccount')),
            ],
            options={
                'db_table': 'journal_lines',
                'ordering': ['id'],
            },
        ),
    ]
