# Generated by Django 6.1.1 on 2026-09-24 07:27

import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ledgeraccount_loan_credit_grade_loan_credit_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('basis', models.CharField(choices=[('percent', 'Percent of principal'), ('fixed', 'Fixed amount')], default='fixed', max_length=10)),
                ('value', models.DecimalField(decimal_places=4, help_text='A percentage when the basis is percent, otherwise an amount', max_digits=14)),
                ('timing', models.CharField(choices=[('disbursement', 'Deducted at disbursement'), ('manual', 'Raised manually')], default='disbursement', max_length=14)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'charges',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SavingsProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('interest_rate_pct_pa', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Annual rate, credited monthly', max_digits=6)),
                ('min_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('allow_withdrawals', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'savings_products',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total of the catalogue charges on this loan', max_digits=14),
        ),
        migrations.AddField(
            model_name='loan',
            name='refinanced_from',
            field=models.ForeignKey(blank=True, help_text='The loan this one tops up and settles', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refinanced_into', to='core.loan'),
        ),
        migrations.AddField(
            model_name='organisationsetting',
            name='group_arrears_block_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(choices=[('disbursement', 'Disbursement'), ('repayment', 'Repayment'), ('penalty', 'Penalty'), ('fee', 'Fee'), ('charge', 'Charge collected'), ('waiver', 'Waiver'), ('write_off', 'Write-off'), ('recovery', 'Recovery after write-off'), ('reversal', 'Reversal')], max_length=20),
        ),
        migrations.CreateModel(
            name='BorrowerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('meeting_day', models.CharField(blank=True, max_length=12, null=True)),
                ('meeting_place', models.CharField(blank=True, max_length=160, null=True)),
                ('formed_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('forming', 'Forming'), ('active', 'Active'), ('dormant', 'Dormant'), ('closed', 'Closed')], db_index=True, default='forming', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower_groups', to='core.branch')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'borrower_groups',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Set when the loan is taken under joint liability', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='core.borrowergroup'),
        ),
        migrations.CreateModel(
            name='LoanCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Snapshot, so history survives a rename', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('applied_on', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_charges', to='core.charge')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='core.loan')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_charges', to='core.transaction')),
            ],
            options={
                'db_table': 'loan_charges',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('closed', 'Closed')], db_index=True, default='active', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('opened_on', models.DateField(default=datetime.date.today)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('last_interest_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_accounts', to='core.borrower')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_accounts', to='core.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='core.savingsproduct')),
            ],
            options={
                'db_table': 'savings_accounts',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('interest', 'Interest credited'), ('fee', 'Account fee'), ('reversal', 'Reversal')], max_length=12)),
                ('txn_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('salary_deduction', 'Salary deduction')], max_length=20, null=True)),
                ('reference', models.CharField(blank=True, max_length=80, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('reversed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.savingsaccount')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_postings', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='core.savingstransaction')),
            ],
            options={
                'db_table': 'savings_transactions',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='savings_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='core.savingstransaction'),
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Chairperson'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('member', 'Member')], default='member', max_length=12)),
                ('joined_on', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='core.borrower')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.borrowergroup')),
            ],
            options={
                'db_table': 'group_members',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('group', 'borrower'), name='uq_group_member')],
            },
        ),
        migrations.CreateModel(
            name='ProductCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_charges', to='core.charge')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_charges', to='core.loanproduct')),
            ],
            options={
                'db_table': 'product_charges',
                'constraints': [models.UniqueConstraint(fields=('product', 'charge'), name='uq_product_charge')],
            },
        ),
    ]
