# Generated by Django 6.1.1 on 2026-09-24 08:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_charge_savingsproduct_loan_other_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalment',
            name='charge_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fees added to this instalment mid-term', max_digits=14),
        ),
        migrations.AddField(
            model_name='instalment',
            name='charge_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='loan',
            name='charges_outstanding',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='loancharge',
            name='collection',
            field=models.CharField(choices=[('counter', 'Collected at the counter'), ('balance', 'Added to the loan balance')], default='counter', max_length=10),
        ),
        migrations.AddField(
            model_name='loancharge',
            name='instalment',
            field=models.ForeignKey(blank=True, help_text='Set when the charge was added to the balance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='core.instalment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='charge_component',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(choices=[('disbursement', 'Disbursement'), ('repayment', 'Repayment'), ('penalty', 'Penalty'), ('fee', 'Fee'), ('charge', 'Charge collected'), ('charge_added', 'Charge added to the balance'), ('waiver', 'Waiver'), ('write_off', 'Write-off'), ('recovery', 'Recovery after write-off'), ('reversal', 'Reversal')], max_length=20),
        ),
    ]
