# Generated by Django 6.1.1 on 2026-09-24 12:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_instalment_charge_due_instalment_charge_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='provision_held',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.CreateModel(
            name='ProvisionRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('reversed', 'Reversed')], default='posted', max_length=10)),
                ('loans_assessed', models.IntegerField(default=0)),
                ('loans_released', models.IntegerField(default=0)),
                ('total_exposure', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_carrying_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('provision_required', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('provision_before', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('movement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('ledger_provision_before', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('stage1_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('stage2_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('stage3_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('stage2_days', models.IntegerField(default=0)),
                ('stage3_days', models.IntegerField(default=0)),
                ('narration', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provision_run', to='core.journalentry')),
                ('reversal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provision_reversal', to='core.journalentry')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_provision_runs', to=settings.AUTH_USER_MODEL)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provision_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provision_runs',
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProvisionRunLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('closed', 'Closed'), ('written_off', 'Written off')], max_length=20)),
                ('stage', models.CharField(blank=True, choices=[('1', 'Stage 1 - performing'), ('2', 'Stage 2 - significant increase in credit risk'), ('3', 'Stage 3 - credit impaired')], max_length=1, null=True)),
                ('days_past_due', models.IntegerField(default=0)),
                ('exposure', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('carrying_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('provision_required', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('provision_before', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('provision_after', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('movement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provision_lines', to='core.loan')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.provisionrun')),
            ],
            options={
                'db_table': 'provision_run_lines',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='provisionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'posted')), fields=('period_end',), name='uq_provision_run_posted_period'),
        ),
        migrations.AddConstraint(
            model_name='provisionrunline',
            constraint=models.UniqueConstraint(fields=('run', 'loan'), name='uq_provision_run_loan'),
        ),
    ]
