# Generated by Django 6.1.1 on 2026-09-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_loan_provision_held_provisionrun_provisionrunline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(choices=[('disbursement', 'Disbursement'), ('repayment', 'Repayment'), ('penalty', 'Penalty'), ('fee', 'Fee'), ('charge', 'Charge collected'), ('charge_added', 'Charge added to the balance'), ('capitalisation', 'Capitalised on reschedule'), ('waiver', 'Waiver'), ('write_off', 'Write-off'), ('recovery', 'Recovery after write-off'), ('reversal', 'Reversal')], max_length=20),
        ),
    ]
