# Generated by Django 6.1.1 on 2026-09-24 14:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transaction_txn_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='closed', max_length=8)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True, null=True)),
                ('reopen_count', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('snapshot_debits', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('snapshot_credits', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('snapshot_entries', models.IntegerField(default=0)),
                ('snapshot_principal_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('snapshot_savings_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('snapshot_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods_closed', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods_reopened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounting_periods',
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='uq_accounting_period'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='ck_period_month')],
            },
        ),
    ]
