# Generated by Django 6.1.1 on 2026-09-30 10:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_accountingperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(help_text='The transaction type that raised it', max_length=32),
        ),
        migrations.CreateModel(
            name='CapitalTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('injection', 'Capital injection'), ('return_of_capital', 'Return of capital'), ('dividend', 'Dividend'), ('reversal', 'Reversal')], max_length=20)),
                ('txn_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contributor', models.CharField(help_text='Who put the money in — a snapshot, so history survives a rename', max_length=160)),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('salary_deduction', 'Salary deduction')], max_length=20, null=True)),
                ('reference', models.CharField(blank=True, max_length=80, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('reversed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_transactions', to='core.branch')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_postings', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='core.capitaltransaction')),
            ],
            options={
                'db_table': 'capital_transactions',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='capital_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='core.capitaltransaction'),
        ),
        migrations.CreateModel(
            name='FacilityTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('drawdown', 'Drawdown'), ('repayment', 'Principal repayment'), ('interest_accrual', 'Interest accrued'), ('interest_payment', 'Interest paid'), ('fee', 'Facility fee'), ('reversal', 'Reversal')], max_length=20)),
                ('txn_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('principal_after', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('accrued_after', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('salary_deduction', 'Salary deduction')], max_length=20, null=True)),
                ('reference', models.CharField(blank=True, max_length=80, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('reversed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_postings', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='core.facilitytransaction')),
            ],
            options={
                'db_table': 'facility_transactions',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='facility_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='core.facilitytransaction'),
        ),
        migrations.CreateModel(
            name='FundingFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('funder_name', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('facility_limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate_pct_pa', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('is_revolving', models.BooleanField(default=False, help_text='A revolving facility frees its limit as principal is repaid')),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('repayment_terms', models.CharField(blank=True, max_length=200, null=True)),
                ('principal_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('interest_accrued', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('last_accrual_date', models.DateField(blank=True, null=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'funding facilities',
                'db_table': 'funding_facilities',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='facilitytransaction',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.fundingfacility'),
        ),
        migrations.AddField(
            model_name='loan',
            name='funding_facility',
            field=models.ForeignKey(blank=True, help_text='The facility this advance was funded from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='core.fundingfacility'),
        ),
    ]
