# Generated by Django 6.1.1 on 2026-09-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_journalentry_source_capitaltransaction_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='instalment',
            index=models.Index(fields=['due_date', 'loan'], include=('principal_due', 'interest_due', 'penalty_due', 'charge_due', 'principal_paid', 'interest_paid', 'penalty_paid', 'charge_paid', 'status'), name='ix_inst_due_loan_cover'),
        ),
    ]
