# Generated by Django 6.1.1 on 2026-10-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_token_version_revokedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'scheduled_for'], name='ix_notif_status_due'),
        ),
    ]
