# Generated by Django 6.1.1 on 2026-10-01 18:32

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notification_attempts_notification_last_attempt_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('credit', 'Credit'), ('liquidity', 'Liquidity and funding'), ('operational', 'Operational'), ('fraud', 'Fraud'), ('compliance', 'Compliance and regulatory'), ('technology', 'Technology and data'), ('people', 'People'), ('strategic', 'Strategic'), ('reputational', 'Reputational')], db_index=True, default='operational', max_length=20)),
                ('inherent_likelihood', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('inherent_impact', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('controls', models.TextField(blank=True, null=True)),
                ('residual_likelihood', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_impact', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('treatment', models.CharField(choices=[('treat', 'Treat - reduce it'), ('tolerate', 'Tolerate - accept it'), ('transfer', 'Transfer - insure or contract it out'), ('terminate', 'Terminate - stop the activity')], default='treat', max_length=12)),
                ('action_plan', models.TextField(blank=True, null=True)),
                ('action_due', models.DateField(blank=True, null=True)),
                ('review_every_months', models.IntegerField(default=3)),
                ('next_review_on', models.DateField(db_index=True)),
                ('last_reviewed_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=10)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('closed_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='core.branch')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_risks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risks',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RiskReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_on', models.DateField(default=datetime.date.today)),
                ('residual_likelihood', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_impact', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note', models.TextField()),
                ('next_review_on', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_reviews', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.risk')),
            ],
            options={
                'db_table': 'risk_reviews',
                'ordering': ['-reviewed_on', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='risk',
            constraint=models.CheckConstraint(condition=models.Q(('inherent_impact__gte', 1), ('inherent_impact__lte', 5), ('inherent_likelihood__gte', 1), ('inherent_likelihood__lte', 5), ('residual_impact__gte', 1), ('residual_impact__lte', 5), ('residual_likelihood__gte', 1), ('residual_likelihood__lte', 5)), name='ck_risk_rating_scale'),
        ),
        migrations.AddConstraint(
            model_name='risk',
            constraint=models.CheckConstraint(condition=models.Q(('residual_impact__lte', models.F('inherent_impact')), ('residual_likelihood__lte', models.F('inherent_likelihood'))), name='ck_risk_residual_within_inherent'),
        ),
    ]
