# Generated by Django 6.1.1 on 2026-10-03 13:02

from django.db import migrations, models


def link_existing_guarantors(apps, schema_editor):
    """Every existing loan keeps the guarantors its agreement already listed.

    Before this, the agreement printed all of the borrower's guarantors, so linking
    each loan to all of them changes nothing anyone has already printed or signed.
    New loans choose theirs at application.
    """
    Loan = apps.get_model("core", "Loan")
    Guarantor = apps.get_model("core", "Guarantor")
    Link = Loan.guarantors.through
    by_borrower = {}
    for guarantor_id, borrower_id in Guarantor.objects.values_list("id", "borrower_id"):
        by_borrower.setdefault(borrower_id, []).append(guarantor_id)
    links = [Link(loan_id=loan_id, guarantor_id=guarantor_id)
             for loan_id, borrower_id in Loan.objects.values_list("id", "borrower_id")
             for guarantor_id in by_borrower.get(borrower_id, [])]
    Link.objects.bulk_create(links, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_loan_apr'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='guarantors',
            field=models.ManyToManyField(blank=True, db_table='loan_guarantors', related_name='loans', to='core.guarantor'),
        ),
        migrations.RunPython(link_existing_guarantors, migrations.RunPython.noop),
    ]
