# Generated by Django 6.1.1 on 2026-10-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_loan_guarantors'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='repayment_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('fortnightly', 'Fortnightly'), ('weekly', 'Weekly')], default='monthly', help_text='Snapshot from the product at application', max_length=12),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='repayment_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('fortnightly', 'Fortnightly'), ('weekly', 'Weekly')], default='monthly', help_text='How often instalments fall. The rate stays a monthly rate whatever this is', max_length=12),
        ),
    ]
