# Generated by Django 6.1.1 on 2026-10-03 13:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


NEW_ACCOUNTS = [
    ("1500", "Other receivables and prepayments", "asset", "Deposits paid, prepaid rent and other amounts owed to the institution"),
    ("1600", "Property and equipment", "asset", "Vehicles, computers, furniture, at cost"),
    ("1690", "Accumulated depreciation", "asset", "Contra-asset; carries a credit balance against 1600"),
    ("2900", "Accruals and other payables", "liability", "Bills received or expenses incurred and not yet paid"),
    ("3900", "Opening balances", "equity", "Balances brought forward from a previous system; clear to retained earnings once agreed"),
    ("4900", "Other income", "income", "Income outside the loan book, and cash over at the tills"),
    ("6000", "Staff costs", "expense", "Salaries, wages, allowances and statutory contributions"),
    ("6100", "Rent and premises", "expense", "Rent, rates, utilities, security and cleaning"),
    ("6200", "Transport and travel", "expense", "Fuel, vehicle running costs and field travel"),
    ("6300", "Communication and IT", "expense", "Airtime, data, SMS gateway, software and hosting"),
    ("6400", "Professional fees", "expense", "Audit, legal, consulting and regulatory fees"),
    ("6500", "Office and administration", "expense", "Stationery, printing, postage and sundries"),
    ("6600", "Bank charges", "expense", "Bank and mobile-money transaction charges"),
    ("6700", "Depreciation", "expense", "The year's charge against property and equipment"),
    ("6800", "Cash shortages", "expense", "Cash short at the tills, written off on verification"),
    ("6900", "Other operating expenses", "expense", "Anything without a better home; review it monthly"),
]


def add_operating_accounts(apps, schema_editor):
    """Give a book that already has a chart of accounts somewhere to post expenses.

    Only where the chart exists: a fresh database gets the whole chart from Rebuild
    or the seed command, exactly as before. A copy of the list rather than an
    import, so this migration means the same thing whatever ledger.py later says.
    """
    LedgerAccount = apps.get_model("core", "LedgerAccount")
    if not LedgerAccount.objects.filter(code="1000").exists():
        return
    for code, name, kind, description in NEW_ACCOUNTS:
        LedgerAccount.objects.get_or_create(
            code=code, defaults={"name": name, "type": kind, "description": description})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_repayment_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('entry_date', models.DateField(db_index=True)),
                ('narration', models.TextField()),
                ('reference', models.CharField(blank=True, help_text='Invoice, receipt or payslip number', max_length=80, null=True)),
                ('status', models.CharField(choices=[('draft', 'Awaiting approval'), ('posted', 'Posted'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], db_index=True, default='draft', max_length=10)),
                ('prepared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_journals', to='core.branch')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_journal', to='core.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals_posted', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals_prepared', to=settings.AUTH_USER_MODEL)),
                ('reversal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_journal_reversal', to='core.journalentry')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals_reversed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manual_journals',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ManualJournalLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_journal_lines', to='core.ledgeraccount')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.manualjournal')),
            ],
            options={
                'db_table': 'manual_journal_lines',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='ck_manual_line_one_side')],
            },
        ),
        migrations.RunPython(add_operating_accounts, migrations.RunPython.noop),
    ]
