# Generated by Django 6.1.1 on 2026-10-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_manual_journals'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='external_ref',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(choices=[('disbursement', 'Disbursement'), ('repayment', 'Repayment'), ('penalty', 'Penalty'), ('fee', 'Fee'), ('charge', 'Charge collected'), ('charge_added', 'Charge added to the balance'), ('capitalisation', 'Capitalised on reschedule'), ('waiver', 'Waiver'), ('write_off', 'Write-off'), ('recovery', 'Recovery after write-off'), ('reversal', 'Reversal'), ('opening_balance', 'Opening balance brought forward')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref__isnull', False)), fields=('external_ref',), name='uq_loan_external_ref'),
        ),
    ]
