# Generated by Django 6.1.1 on 2026-10-03 19:41

import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_loan_book_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsetting',
            name='require_open_till',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TillSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('business_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opening_float', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('counted', 'Counted, awaiting verification'), ('verified', 'Verified')], db_index=True, default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cash_in', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cash_out', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, help_text='Counted less expected: negative is a shortage', max_digits=14, null=True)),
                ('close_note', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verify_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tills', to='core.branch')),
                ('teller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tills', to=settings.AUTH_USER_MODEL)),
                ('variance_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='till_session', to='core.journalentry')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tills_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'till_sessions',
                'ordering': ['-opened_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('teller',), name='uq_till_one_open_per_teller')],
            },
        ),
    ]
