# Generated by Django 6.1.1 on 2026-10-03 19:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tills'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('account_name', models.CharField(help_text='Which bank or wallet account this is', max_length=120)),
                ('channel', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('salary_deduction', 'Salary deduction')], default='bank_transfer', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_statements',
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StatementLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('txn_date', models.DateField(db_index=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('ignored', 'Ignored')], db_index=True, default='unmatched', max_length=10)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('auto_matched', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_line', to='core.journalentry')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_lines_matched', to=settings.AUTH_USER_MODEL)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.bankstatement')),
            ],
            options={
                'db_table': 'statement_lines',
                'ordering': ['line_no'],
                'constraints': [models.UniqueConstraint(fields=('statement', 'line_no'), name='uq_statement_line_no')],
            },
        ),
    ]
