# Generated by Django 6.1.1 on 2026-10-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_two_factor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='risk',
            name='ck_risk_rating_scale',
        ),
        migrations.RemoveConstraint(
            model_name='risk',
            name='ck_risk_residual_within_inherent',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='raised_by',
        ),
        migrations.DeleteModel(
            name='RiskReview',
        ),
        migrations.DeleteModel(
            name='Risk',
        ),
    ]
