# Generated by Django 5.2.17 on 2026-10-05 18:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_holiday_calendar"),
    ]

    operations = [
        migrations.CreateModel(
            name="BureauEnquiry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "Report received"), ("failed", "Failed")],
                        default="ok",
                        max_length=10,
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="The bureau's own reference for the report",
                        max_length=80,
                        null=True,
                    ),
                ),
                ("score", models.IntegerField(blank=True, null=True)),
                ("score_max", models.IntegerField(default=1000)),
                ("open_accounts", models.IntegerField(default=0)),
                ("accounts_in_arrears", models.IntegerField(default=0)),
                ("defaults", models.IntegerField(default=0)),
                ("worst_days_in_arrears", models.IntegerField(default=0)),
                (
                    "total_exposure",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Owed to other lenders",
                        max_digits=14,
                    ),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "detail",
                    models.TextField(
                        blank=True, help_text="JSON: the figures as received", null=True
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "enquired_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bureau_enquiries",
                        to="core.borrower",
                    ),
                ),
                (
                    "enquired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        help_text="The application it was run for, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bureau_enquiries",
                        to="core.loan",
                    ),
                ),
            ],
            options={
                "db_table": "bureau_enquiries",
                "ordering": ["-enquired_at", "-id"],
            },
        ),
    ]
