# Generated by Django 6.1.1 on 2026-10-05 13:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_holiday_calendar"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomingPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=40)),
                ("reference", models.CharField(max_length=80)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("received_on", models.DateField()),
                ("account", models.CharField(blank=True, max_length=80, null=True)),
                ("payer_phone", models.CharField(blank=True, max_length=30, null=True)),
                ("payer_name", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "payload",
                    models.TextField(
                        help_text="The body exactly as the provider sent it"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("posted", "Posted to a loan"),
                            ("unmatched", "Waiting for someone to place it"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="unmatched",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_payments",
                        to="core.loan",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_payment",
                        to="core.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "incoming_payments",
                "ordering": ["-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "reference"),
                        name="uq_incoming_payment_provider_ref",
                    )
                ],
            },
        ),
    ]
