# Generated by Django 6.1.1 on 2026-10-05 13:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_incoming_payments"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceClaim",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim_no", models.CharField(max_length=20, unique=True)),
                (
                    "cause",
                    models.CharField(
                        choices=[
                            ("death", "Death"),
                            ("disability", "Permanent disability"),
                            ("retrenchment", "Retrenchment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_date", models.DateField()),
                ("lodged_on", models.DateField()),
                (
                    "amount_claimed",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "insurer_reference",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lodged", "Lodged with the insurer"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="lodged",
                        max_length=20,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("paid_on", models.DateField(blank=True, null=True)),
                (
                    "remainder_written_off",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="core.loan",
                    ),
                ),
                (
                    "lodged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claim",
                        to="core.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "insurance_claims",
                "ordering": ["-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "lodged")),
                        fields=("loan",),
                        name="uq_claim_one_open_per_loan",
                    )
                ],
            },
        ),
    ]
