# Generated by Django 5.2.17 on 2026-10-05 18:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_bureau_enquiries"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="currency",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="loan",
            name="fx_rate",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("1"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="currency",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Blank for the organisation's currency",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="book_rate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="fx_rate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.CreateModel(
            name="RevaluationRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_no", models.CharField(db_index=True, max_length=20, unique=True)),
                ("as_of", models.DateField(db_index=True)),
                ("base_currency", models.CharField(max_length=8)),
                ("loans_revalued", models.IntegerField(default=0)),
                (
                    "movement",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Net change in the receivables, base currency",
                        max_digits=14,
                    ),
                ),
                ("narration", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revaluation_run",
                        to="core.journalentry",
                    ),
                ),
                (
                    "run_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "revaluation_runs",
                "ordering": ["-as_of", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RevaluationLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=8)),
                ("old_rate", models.DecimalField(decimal_places=6, max_digits=18)),
                ("new_rate", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "principal_outstanding",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "penalties_outstanding",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "charges_outstanding",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "principal_movement",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "penalties_movement",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "charges_movement",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "movement",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revaluation_lines",
                        to="core.loan",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="core.revaluationrun",
                    ),
                ),
            ],
            options={
                "db_table": "revaluation_lines",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=8)),
                ("rate_date", models.DateField(db_index=True)),
                ("rate", models.DecimalField(decimal_places=6, max_digits=18)),
                ("note", models.CharField(blank=True, max_length=120, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exchange_rates",
                "ordering": ["-rate_date", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "rate_date"), name="uq_exchange_rate_code_date"
                    )
                ],
            },
        ),
    ]
