# Generated by Django 5.2.17 on 2026-10-05 18:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_multi_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="instalment",
            name="accrued_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="fees_deferred",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="interest_accrued",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="organisationsetting",
            name="interest_method",
            field=models.CharField(
                choices=[
                    ("collected", "When collected"),
                    ("effective", "Effective interest method (IFRS 9)"),
                ],
                default="collected",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="revaluationline",
            name="fees_deferred",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="revaluationline",
            name="fees_movement",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="revaluationline",
            name="interest_movement",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="revaluationline",
            name="interest_receivable",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="txn_type",
            field=models.CharField(
                choices=[
                    ("disbursement", "Disbursement"),
                    ("repayment", "Repayment"),
                    ("penalty", "Penalty"),
                    ("fee", "Fee"),
                    ("charge", "Charge collected"),
                    ("charge_added", "Charge added to the balance"),
                    ("capitalisation", "Capitalised on reschedule"),
                    ("waiver", "Waiver"),
                    ("write_off", "Write-off"),
                    ("recovery", "Recovery after write-off"),
                    ("reversal", "Reversal"),
                    ("accrual", "Interest accrued"),
                    ("opening_balance", "Opening balance brought forward"),
                ],
                max_length=20,
            ),
        ),
    ]
