# Generated by Django 6.1.2 on 2026-10-06 18:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_saved_views"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tillsession",
            name="uq_till_one_open_per_teller",
        ),
        migrations.AddField(
            model_name="facilitytransaction",
            name="book_rate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="facilitytransaction",
            name="fx_rate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="fundingfacility",
            name="currency",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="fundingfacility",
            name="fx_rate",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("1"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="revaluationline",
            name="borrowing_interest",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="revaluationline",
            name="borrowing_interest_movement",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="revaluationline",
            name="borrowings",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="revaluationline",
            name="borrowings_movement",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="revaluationline",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revaluation_lines",
                to="core.fundingfacility",
            ),
        ),
        migrations.AddField(
            model_name="revaluationline",
            name="savings_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revaluation_lines",
                to="core.savingsaccount",
            ),
        ),
        migrations.AddField(
            model_name="revaluationline",
            name="savings_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="revaluationline",
            name="savings_movement",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="revaluationrun",
            name="facilities_revalued",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="revaluationrun",
            name="savings_revalued",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="savingsaccount",
            name="currency",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="savingsaccount",
            name="fx_rate",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("1"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="savingsproduct",
            name="currency",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Blank for the organisation's currency",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="savingstransaction",
            name="book_rate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="savingstransaction",
            name="fx_rate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="tillsession",
            name="currency",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="tillsession",
            name="fx_rate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="revaluationline",
            name="loan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revaluation_lines",
                to="core.loan",
            ),
        ),
        migrations.AlterField(
            model_name="revaluationrun",
            name="movement",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Net unrealised gain, a loss negative; base currency",
                max_digits=14,
            ),
        ),
        migrations.AddConstraint(
            model_name="tillsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("teller", "currency"),
                name="uq_till_one_open_per_teller_currency",
            ),
        ),
    ]
