# Generated by Django 6.1.1 on 2026-10-07 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_foreign_savings_funding_tills'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='preferred_channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='sms', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='fallback_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallbacks', to='core.notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='template_vars',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='sms', max_length=10),
        ),
    ]
