# Generated by Django 6.1.1 on 2026-10-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_whatsapp_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsetting',
            name='communication_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='preferred_channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='sms', max_length=10),
        ),
    ]
