# Generated by Django 6.1.1 on 2026-10-07 10:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_communication_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('national_id', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.TextField(blank=True, default='')),
                ('employer', models.CharField(blank=True, default='', max_length=120)),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payday', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('term_months', models.IntegerField()),
                ('purpose', models.CharField(blank=True, default='', max_length=200)),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='new', max_length=10)),
                ('outcome', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(default='public', max_length=10)),
                ('client_address', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_applications', to='core.borrower')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.loan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.loanproduct')),
            ],
            options={
                'db_table': 'online_applications',
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
