# Generated by Django 6.1.1 on 2026-10-07 10:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_online_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('aliases', models.TextField(blank=True, default='')),
                ('date_of_birth', models.CharField(blank=True, default='', max_length=40)),
                ('id_number', models.CharField(blank=True, default='', max_length=80)),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('keys', models.TextField(blank=True, default='')),
                ('loaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'watchlist_entries',
            },
        ),
        migrations.AddField(
            model_name='borrower',
            name='is_pep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrower',
            name='screened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ScreeningHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=40)),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('score', models.IntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('open', 'To review'), ('cleared', 'Not the same person'), ('confirmed', 'Confirmed match')], db_index=True, default='open', max_length=10)),
                ('review_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_hits', to='core.borrower')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hits', to='core.watchlistentry')),
            ],
            options={
                'db_table': 'screening_hits',
                'ordering': ['status', '-score'],
                'constraints': [models.UniqueConstraint(fields=('borrower', 'source', 'listed_name'), name='uq_hit_borrower_listing')],
            },
        ),
    ]
