# Generated by Django 6.1.1 on 2026-10-07 10:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_aml_screening'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='borrower',
            name='bank_account_no',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='borrower',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='borrower',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='borrower',
            name='mobile_wallet',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('salary_deduction', 'Salary deduction')], max_length=20)),
                ('payee_name', models.CharField(max_length=160)),
                ('account', models.CharField(max_length=60)),
                ('bank_name', models.CharField(blank=True, default='', max_length=80)),
                ('bank_branch', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'To pay'), ('sent', 'Sent'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('batch', models.CharField(blank=True, default='', max_length=40)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=120)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='core.loan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payouts',
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
