# Generated by Django 6.1.1 on 2026-10-07 13:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_payouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='test_redirect',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('reminder', 'Instalment reminder'), ('arrears', 'Arrears notice'), ('receipt', 'Repayment receipt'), ('welcome', 'Disbursement confirmation'), ('signing_code', 'Agreement signing code'), ('portal_code', 'Portal sign-in code'), ('bulk', 'Bulk message')], max_length=20),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('audience', models.JSONField(default=dict)),
                ('channel', models.CharField(default='preferred', max_length=10)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('text', models.TextField()),
                ('scheduled_for', models.DateField()),
                ('queued', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.campaign'),
        ),
    ]
