# Generated by Django 6.1.1 on 2026-10-08 08:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_bulk_messages_and_test_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='business_address',
            field=models.TextField(blank=True, default='', help_text='Where the business operates'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='business_name',
            field=models.CharField(blank=True, default='', help_text='The business, or the trade (e.g. vegetable vending, Mbare)', max_length=120),
        ),
        migrations.AddField(
            model_name='borrower',
            name='business_registration_no',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='borrower',
            name='business_sector',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='borrower',
            name='income_source',
            field=models.CharField(choices=[('employed', 'Employed (salary)'), ('self_employed', 'Own business'), ('informal', 'Informal trader'), ('farmer', 'Farmer')], default='employed', max_length=14),
        ),
        migrations.AddField(
            model_name='borrower',
            name='monthly_cost_of_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Stock and materials', max_digits=14),
        ),
        migrations.AddField(
            model_name='borrower',
            name='monthly_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Rent, wages, transport, power and the like', max_digits=14),
        ),
        migrations.AddField(
            model_name='borrower',
            name='monthly_other_repayments',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Repayments to other lenders', max_digits=14),
        ),
        migrations.AddField(
            model_name='borrower',
            name='monthly_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='borrower',
            name='trading_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='max_instalment_to_business_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text="Most of a business owner's net monthly income the repayments may take", max_digits=6),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='income_source',
            field=models.CharField(choices=[('employed', 'Employed (salary)'), ('self_employed', 'Own business'), ('informal', 'Informal trader'), ('farmer', 'Farmer')], default='employed', max_length=14),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='payday',
            field=models.IntegerField(default=25, help_text='Day of the month the salary is paid, or the business is best placed to pay', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
